[build]
  base = "blogplatform-frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://occasion-applying-louisiana-ruth.trycloudflare.com"

[context.deploy-preview.environment]
  VITE_API_BASE = "https://occasion-applying-louisiana-ruth.trycloudflare.com"

[context.branch-deploy.environment]
  VITE_API_BASE = "https://occasion-applying-louisiana-ruth.trycloudflare.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
