[build]
  base = "blogplatform-frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://finals-replacement-camel-acknowledge.trycloudflare.com"

[[redirects]]
  from = "/api/*"
  to = "https://localhost:7141/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
