[build]
  base = "blogplatform-frontend"
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "blogplatform-frontend/dist"
  branch = "main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200